version: '3'
services:
  zoo1:
    container_name: zookeeper1
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./z1/data:/data
      - ./z1/datalog:/datalog

  zoo2:
    container_name: zookeeper2
    image: zookeeper
    restart: always
    hostname: zoo2
      #ports:
      #- 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./z2/data:/data
      - ./z2/datalog:/datalog

  zoo3:
    container_name: zookeeper3
    image: zookeeper
    restart: always
    hostname: zoo3
      #ports:
      #- 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./z3/data:/data
      - ./z3/datalog:/datalog
