version: '3'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_data/:/prometheus/
      - ./prometheus_conf/:/etc/prometheus/
    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager_conf/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana/
      - ./grafana_conf:/usr/share/grafana/conf/

  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway
    restart: always
    ports:
      - 9091:9091

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter
    restart: always
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro,rslave

  cAdvisor:
    container_name: cadvisor
    image: "lagoudocker/cadvisor:v0.37.0"
    restart: always
    ports:
      - 6001:8080
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:rw
      - /dev/disk/:/dev/disk:ro
