version: '3'
services:
  kafka-zookeeper:
    container_name: kafka-zookeeper
    image: wurstmeister/zookeeper
    restart: always
    hostname: zookeeper
    ports:
      - 12181:2181
    volumes:
      - ./zk/data:/data
      - ./zk/datalog:/datalog

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    restart: always
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_CERATE_TOPICS: "topic1:1:1"
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
    links:
      - kafka-zookeeper

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
      - 19092:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=dev_cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    links:
      - kafka

  kafka_exporter:
    container_name: kafka_expoter
    image: danielqsj/kafka-exporter
    restart: always
    ports:
      - 9308:9308
    environment:
      KAFKA_SERVER: kafka:9092
    links:
      - kafka
