version: '3'
services:
  redis:
    container_name: redis-1
    image: redis:7.0.8
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis_conf:/usr/local/etc/redis/
      - ./redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis_exporter:
    container_name: redis_exporter
    image: oliver006/redis_exporter
    restart: always
    command:
      - --redis.addr=redis://redis
      - --redis.password=123456
    ports:
      - 9121:9121
    links:
      - redis
