version: '3.1'
services:
  leanote:
    container_name: leanote
    image: axboy/leanote
    restart: always
    volumes:
      - ./data/db:/data/db
      - ./data/conf/:/data/leanote/conf
      - ./data/files:/data/leanote/files
      - ./data/upload/:/data/leanote/public/upload
    ports:
      - 19999:9000

