version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres:15.7
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
      - ./postgresql_logs:/var/log/postgresql
  postgresql_export:
    container_name: postgresql_export
    image: wrouesnel/postgres_exporter
    restart: always
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:123456@postgresql:5432/?sslmode=disable"
    links:
      - postgresql
