version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
    ports:
      - 3306:3306

  mysql_export:
    container_name: mysql_export
    image: prom/mysqld-exporter
    restart: always
    ports:
      - 9104:9104
    volumes:
      - ./mysql_export_conf/my.cnf:/home/.my.cnf
    command:
      - --config.my-cnf=/home/.my.cnf
    links:
      - mysql
